---
title: "Bayes"
author: "GPF"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
```

```{r packages}
needed_packages = c("invgamma", "cmdstanr", "HDInterval", "bayesplot","BiocManager","modeest", 'kableExtra', 'formattable', 'tidyverse')
for(i in 1:length(needed_packages)){
  haspackage = require(needed_packages[i], character.only = TRUE)
  if(haspackage == FALSE){
    install.packages(needed_packages[i])
  }
  library(needed_packages[i], character.only = TRUE)
}
rm(haspackage, needed_packages, i)
```

## Data
```{r}
# full data set
d <- read.csv(file = "https://raw.githubusercontent.com/Fran-Diaz-R/Bayes/main/data_full.csv")

# some data manipulation / item represents pairwise comparison
d <- d %>% mutate(
  item = paste(areaIncorrect, numIncorrect, sep = '_'),
  item = as.numeric(factor(item))) %>%
  arrange(item)

# we have balanced data per pidgeon, session and item
d %>% group_by(bird) %>% summarise(min_i = min(item),
                                   max_i = max(item),
                                   min_s = min(session),
                                   max_s = max(session))
#there is no missing data
sum(is.na(d$accuracy))

# important variables
data <- d %>% select(bird, accuracy, session, Euclidean, CityBlock, item)
colnames(data) <- c('Bird', 'y', 'Session', 'Euclidean', 'Cityblock', 'Item')
```

## Sample
```{r}
desc <- data %>% group_by(Bird) %>% summarise(
                                   Items = max(Item),
                                   Sessions = max(Session),
                                   Responses = n(),
                                   Avg_Outcome = mean(y))

kable_styling(kable(desc,
                    digits = 3,
                    col.names = c('Bird', 'Items', 'Sessions', 'Responses', 'Avg. Outcomes'),
                    caption = 'Descriptive statistics of sample',
                    align = 'lcccc'),
              bootstrap_options = c('hover', 'responsive', 'bordered'),
              full_width = F, position = 'center', font_size =12)
```

```{r}
itemList = unique(data$Item)[order(unique(data$Item))]
sessionList = unique(data$Session)[order(unique(data$Session))]
#birdList = unique(data$Bird)[order(unique(data$Bird))]

newData = NULL
item = 1
session = 1
bird = 1
for (item in 1:length(itemList)){
  for (session in 1:length(sessionList)){
    for (bird in 1:length(birdList)){
      selectedData = data[which(data$Bird == birdList[bird] &
                                data$Session == sessionList[session] &
                                 data$Item == itemList[item]),]
    newData = rbind(newData,
                    data.frame(
                      y = sum(selectedData$y),
                      e = unique(selectedData$e),
                      c = unique(selectedData$c),
                      b = unique(selectedData$b),
                      s = sessionList[session],
                      item = itemList[item]
                    )
    )
  }
  }
}
```


```{r}
## City-Block Model
CityBlock_Model_Syntax = "

data {
  int<lower=0> nObs;     // rows of observations
  int<lower=0> nItems;   // number of items
  array[nObs] int item;
  vector[nObs] c;
  vector[nObs] session;
  vector[nObs] session2;
  array[nObs] int<lower=0, upper=2> y;
}

parameters {
  real beta0;
   // real betac; -- for next time
  real betaD;
  real betaD2;
  vector[nItems] itemRandomEffect;
  real<lower=0> itemSD;
}

// ## number of successes out of 2 trials (per day)
model {
  beta0 ~ normal(0, 1);
  betaD ~ normal(0, .1);
  betaD2 ~ normal(0, .1);
  itemSD ~ exponential(1);
  itemRandomEffect ~ normal(0, itemSD);
  for (obs in 1:nObs){
    y[obs] ~ binomial(2,inv_logit(beta0 + betaD * session[obs] + itemRandomEffect[item[obs]]));
  }å
  // + betaD * session[obs] + betaD2 * session2[obs]
  // (betaC * cityblock -- for next model
}

//generated quantities (R2)

//Model comparison
//For each value of acc in the iteration, get the LL
"

CityBlock_Model_Stan = cmdstan_model(stan_file = write_stan_file(CityBlock_Model_Syntax))


mode04_StanData = list(
  nObs = nrow(newData),
  nItems = length(itemList)+1,
  item = as.integer(newData$item),
  c = newData$c,
  session = newData$s,
  session2 = newData$s^2,
  y = newData$y
)

CityBlock_Model_Samples = CityBlock_Model_Stan$sample(
  data = mode04_StanData,
  seed = 190920221,
  chains = 4,
  parallel_chains = 4,
  iter_warmup = 400,
  iter_sampling = 400
)

# assess convergence: summary of all parameters

CityBlock_Model_Samples$summary(variables = c("beta0", "betaD", "itemSD"))

```








```{r}
## City-Block Model
CityBlock_Model_Syntax = "

data {
  int<lower=0> N;
  vector[N] c;
  int<lower=0, upper=1> y[N];
}

parameters {
  real beta0;
  real betac;
}

## number of successes out of 2 trials (per day)
model {
  acc ~ binomial(2,inv_logit(alpha + betaC * cityblock + betaD * session));
}

generated quantities (R2)

Model comparison
For each value of acc in the iteration, get the LL
"
```

```{r}
CityBlock_Model_Stan = cmdstan_model(stan_file = write_stan_file(CityBlock_Model_Syntax))

mode04_StanData = list(
  N = nrow(Data),
  acc = Data$accuracy,
  cityblock = Data$CityBlock
)

CityBlock_Model_Samples = CityBlock_Model_Stan$sample(
  data = mode04_StanData,
  seed = 190920221,
  chains = 4,
  parallel_chains = 4,
  iter_warmup = 4000,
  iter_sampling = 4000
)

# assess convergence: summary of all parameters
CityBlock_Model_Samples$summary()

# maximum R-hat
max(CityBlock_Model_Samples$summary()$rhat, na.rm = TRUE)
```


```{r}
## Euclidean Model
Euclidean_Model_Syntax = "
data {
  int<lower=0> N;
  vector[N] Euclidean;
  int<lower=0, upper=1> acc[N];
}

parameters {
  real alpha;
  real beta;
}

model {
  acc ~ bernoulli_logit(alpha + beta * Euclidean);
}

"

Euclidean_Model_Stan = cmdstan_model(stan_file = write_stan_file(Euclidean_Model_Syntax))

mode04_StanData = list(
  N = nrow(Data),
  acc = Data$accuracy,
  Euclidean = Data$Euclidean
)

Euclidean_Model_Samples = Euclidean_Model_Stan$sample(
  data = mode04_StanData,
  seed = 190920221,
  chains = 4,
  parallel_chains = 4,
  iter_warmup = 4000,
  iter_sampling = 4000
)

# assess convergence: summary of all parameters
Euclidean_Model_Samples$summary()

# maximum R-hat
max(Euclidean_Model_Samples$summary()$rhat, na.rm = TRUE)
```
